title: Blog by Eugene Zhlobo
description: Look at my thoughts
author: Eugene Zhlobo

url: http://evgen.zhlobo.info
permalink: blog/:title
category_dir: blog/categories

# Build settings
markdown: kramdown

exclude: ["Gemfile", "Rakefile", "*.rb", "*.md"]
